file = 'PnP_mex.cpp';

INCLUDE = {'/usr/local/include' , '/usr/local/include/eigen3',...
		'/home/lucivpav/ceres-solver-1.14.0/include',...
		'/home/lucivpav/ceres-solver-1.14.0/config',...
	   '/home/lucivpav/gflags-2.2.2/build/include',...
	   '/home/lucivpav/glog-0.4.0/build'};

LIBFOLDER = {'/usr/local/lib/', '/home/lucivpav/gflags-2.2.2/build/lib', ...
			'/home/lucivpav/ceres-solver-1.14.0/build/lib',...
			'/home/lucivpav/glog-0.4.0/build',...
			'/home/lucivpav/lapack-3.8.0/build/lib',...
			'/home/lucivpav/libunwind-1.3.1/install/lib'};

LIBNAME = {'ceres', 'ceres', 'glog', 'gflags', 'suitesparseconfig',...
	   'cholmod', 'lapack', 'blas', 'spqr', 'gomp', 'cxsparse', 'unwind', 'gfortran'};

DEFINE = {'CERES_USE_CXX11_THREADS'};

include = strjoin(strcat('-I', INCLUDE));
libfolder = strjoin(strcat('-L', LIBFOLDER));
libname = strjoin(strcat('-l', LIBNAME));
define = strjoin(strcat('-D', DEFINE));

eval(['mex' ' ' file ' ' include ' '  libfolder ' ' libname ' ' define]);

